#!/bin/bash

R=$1

if [ "$R" = "" ]; then
    echo "Usage: upload-pypi 1.2.3 [test]"
    exit
fi

if [ "$2" = "test" ]; then
    export TWINE_REPOSITORY=testemeraldtree
else
    export TWINE_REPOSITORY=emeraldtree
fi

D=dist/emeraldtree-$R.tar.gz

twine upload "$D"
